training:
    model_name: '1558M'
    train_dir: '../training/training-data.txt'
    eval_dir: 'DMsParsedTest.txt'
    usernames_dir: 'usernames.txt'
    block_size: 256
    plm_probability: 0.166
    output_dir: '../'
    overwrite_output_dir: False
    per_device_train_batch_size: 1
    per_device_eval_batch_size: 1
    gradient_accumulation_steps: 16
    no_cuda: False
    num_train_epochs: 3.0

generation:
    model_name: '1558M'
    seed: 42
    input_string: ''
    bad_words:
        - <kerp>
